name: Convert v2ray domail list to clash rule

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Build clash rules
      run: |
        pnpm install
        pnpm run download
        pnpm run build
        echo "COMMIT_MSG=Released on UTC $(date -u +%Y%m%d%H%M)" >> $GITHUB_ENV
    - name: Deploy to release branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: release
        commit_message: "${{ env.COMMIT_MSG }}"
